### ISSUE TITLE
Not getting services into zabbix

### ISSUE THREAD

**Issue by ramo-karahasan-riechardt** [dmitriy-myz/zabbix-templates#4]
Hi @dmitriy-myz 

I'm running zabbix 4.0

I was trying to copy all the files for consul2zabbix into /opt/scripts on the node where the zabbix server is running.

I uploaded the .xml file to the zabbix frontend and "installed" the template.

I've attached it to a host , but for some reason i'm getting the message. 

```
8742:20181018:182420.790 item "iws-monitoring:consul2zabbix[nodeStatus]" became not supported: Unsupported item key.
  8740:20181018:182501.911 item "iws-monitoring:consul2zabbix[discovery]" became not supported: Unsupported item key.
```

Any idea what I#m doing wrong?

**Comment by dmitriy-myz** [comment]
Hi!
You need to copy `consul2zabbix.py` to `/opt/scripts` on every node, from which you want to collect info. And also `consul2zabbix.py` should be executable
