### ISSUE TITLE
No software license

### ISSUE THREAD

**Issue by mike-sol** [dmitriy-myz/zabbix-templates#5]
Hey there,

I'd really love to be able to use these Zabbix templates and scripts, but because you haven't (to my knowledge) put a software license in place, I'm not allowed to do so according to my legal department.

Would you be willing to select from among the many fine licenses available, e.g. MIT or Apache, and put one on the code?

https://help.github.com/en/articles/adding-a-license-to-a-repository

Thanks kindly!

**Comment by dmitriy-myz** [comment]
Sorry for delay. Licence added

**Comment by mike-sol** [comment]
Fantastic, I really appreciate you doing that and your contribution to the community.
